### ISSUE TITLE
Support separate zoom level for double tap and pinch

### ISSUE THREAD

**Issue by AntsyLich** [saket/telephoto#32]
So when user double taps they'll get a 3x zoom but will be able to zoom upto 5x by pinching

**Comment by saket** [comment]
Agreed, the current spec is not the best for super large images. I need to think of a good API for letting consumers adjust this. Do you have any ideas?

**Comment by AntsyLich** [comment]
Without giving much thought my idea is that you add the zoom levels to zoom spec and maybe keep the current setup as a extra constructor for people who don't need them to be sperate

**Comment by saket** [comment]
The next release will introduce an API for overriding the default double click behavior: 

https://github.com/saket/telephoto/blob/f0201b80d627ba1950ee460db14c132b3406e553/zoomable/src/commonMain/kotlin/me/saket/telephoto/zoomable/Zoomable.kt#L52

**Comment by AntsyLich** [comment]
Can we have `maxDoubleTapZoomFactor` in `ZoomSpec`? The current implementation works but having both values in `ZoomSpec` in my opinion will result in less repetitive code across the eco-system.

**Comment by saket** [comment]
You're right that having a `maxDoubleTapZoomFactor` parameter will be easier, but it will also prevent developers from building other, more complex kinds of double-tap interactions, such as cycling through three levels of zoom.

I wanted to add another `DoubleClickToZoomListener` implementation that takes a `maxZoomFactor` as an argument, but I couldn't think of a good name lol. Suggestions are welcome!

**Comment by saket** [comment]
Available in `0.12.0`: https://github.com/saket/telephoto/releases/tag/0.12.0

**Comment by JonatanPlesko** [comment]
Could you add a recipe for this specific use case somewhere?

I tried to implement the equivalent of ToggleBetweenMinAndMax, substituting `state.zoomSpec.maxZoomFactor` with my desired double tap zoom factor, but I cannot do it exactly like that because `state.contentTransformation.scaleMetadata.initialScale.maxScale` is internal. I tried to substitute the latter with `1f`, and I also tried using `resetZoom` instead, but couldn't get it to work as I'm obviously misunderstanding something about `state.zoomFraction`. I don't know how I'm supposed to use the condition to toggle between _my_ zoom factor and the zoomed out state.

**Comment by saket** [comment]
> I cannot do it exactly like that because state.contentTransformation.scaleMetadata.initialScale.maxScale is internal

Wanna copy over `Scale#maxScale` to your project? you could also safely use `initialScale.scaleX` or `initialScale.scaleY`.

**Comment by JonatanPlesko** [comment]
While that resolves the initial problem, I expect `state.resetZoom()` to be a semantically nicer way of resetting anyway. However, it is still unclear what the correct `zoomFraction` condition for a generic use case is. If I understand correctly, you're using 0.95f because you want to have a little threshold where, if the user _slightly_ zooms out, you're still considering them to be at the max zoom level and zooming _out_ rather than in. 

In a case where the maximum zoom differs from the double-tap zoom, however, one should presumably use `(maxZoom - doubleTapZoom) / maxZoom - 0.05f` or something of the sort to reach the same behaviour. I tried to implement it this way, and it seemingly works okay:

```
onDoubleClick = { state, centroid ->
    val zoomFraction = state.zoomFraction ?: return@ZoomableAsyncImage // Content isn't ready yet.
    if (zoomFraction < ((MAX_ZOOM_FACTOR - DOUBLE_TAP_ZOOM_FACTOR) / MAX_ZOOM_FACTOR - ZOOM_OUT_THRESHOLD)) {
        state.zoomTo(
            zoomFactor = DOUBLE_TAP_ZOOM_FACTOR,
            centroid = centroid,
        )
    } else {
        state.resetZoom()
    }
},
```

I assume this is something that you suggested to expose as a `DoubleClickToZoomListener` implementation earlier. I agree with that idea, or alternatively, I think it would be useful to provide a sample of that implementation in the docs (as a "recipe"?).

As for naming ideas, `ToggleBetweenMinAndCustom` or `ToggleBetweenMinAndCustomZoomFactor` is wordy but consistent with the default naming.

**Comment by saket** [comment]
> I expect state.resetZoom() to be a semantically nicer way of resetting anyway.

You're right. Perhaps I should use `resetZoom()` in the default `DoubleClickToZoomListener` because it's easier to understand.

> If I understand correctly, you're using 0.95f because you want to have a little threshold where, if the user slightly zooms out, you're still considering them to be at the max zoom level and zooming out rather than in.

Correct.

> In a case where the maximum zoom differs from the double-tap zoom, however, one should presumably use `(maxZoom - doubleTapZoom) / maxZoom - 0.05f` or something of the sort to reach the same behaviour. I tried to implement it this way, and it seemingly works okay:

I see what you mean, and I agree that it's slightly confusing to implement your own listener if you're trying to use `zoomFraction`. I'll change the default implementation so that it's easier to follow and modify. In the meantime, you can use this:

```kotlin
class Cycle(val maxZoomFactor: Float) : DoubleClickToZoomListener {
  override suspend fun onDoubleClick(state: ZoomableState, centroid: Offset) {
    val transformation = state.contentTransformation.takeIf { it.isSpecified } ?: return // Content isn't ready yet
    val isAtMaxZoom = maxZoomFactor - transformation.scale.scaleX < 0.05f
    if (isAtMaxZoom) {
      state.resetZoom()
    } else {
      state.zoomTo(
        zoomFactor = maxZoomFactor,
        centroid = centroid,
      )
    }
  }
}
```

**Comment by saket** [comment]
fwiw `DoubleClickToZoomListener.cycle(maxZoomFactor = …)` is now available in the latest snapshot. I'll make a new release soon.

Update: [v0.12.1](https://github.com/saket/telephoto/releases/tag/0.12.1)
