### ISSUE TITLE
Different double tap/zoom functionality

### ISSUE THREAD

**Issue by MV-GH** [saket/telephoto#88]
To allow zooming in a lot, I have set the maxZoomFactor to a high number. As consequence double tap zooms a lot for smaller images. From the feedback that I hear from my users they would like that the double tap, just zooms in incrementally. Instead of going to the max instantly. Rather that it increases the zoom each time by a factor.

Related to #45 

context: https://lemmy.one/post/14467374

**Comment by saket** [comment]
Agree this isn't great right now. Let me merge this with https://github.com/saket/telephoto/issues/32.

**Comment by saket** [comment]
Hey @MV-GH, this should be fixed in [v0.17.0](https://github.com/saket/telephoto/releases/tag/0.17.0). Can you give it a try sometime?

**Comment by MV-GH** [comment]
Hey, is this behaviour now default or is it done through the DoubleClickToZoomListener override ?

**Comment by saket** [comment]
Uhhh, sorry I commented on the wrong issue. While #45 was fixed in the latest release, the default double click listener still zooms to the maximum factor. 

That said, now that smaller images are zoomable, do you still need to set such a high value for your max zoom factor?

<img width="956" height="164" alt="Image" src="https://github.com/user-attachments/assets/8d1ee10c-d719-407f-8ea8-c2115f71e4aa" />

**Comment by MV-GH** [comment]
Is there reason to limit zoom depth?
